spring.application.name=inventory-manager

spring.datasource.url=jdbc:postgresql://dpg-dairehbm8hqs73e0j7m0-a:5432/inventory_db_zswf
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

server.port=${PORT:8080}